### PR TITLE
Fix syntax errors in mail adapter configuration example & use current mailgun adapter setup

### PR DESCRIPTION
**Pull request by funkenstrahlen**

### CODE REVIEW

**Comment by mtrezza** [comment]
Thanks for this PR!

Does this example work for mailgun.js 2.x as well? If not, we may just provide 2 examples, for 2.x, and 3.x, because 3.x has only been release end of Jan 2021.

**Comment by funkenstrahlen** [comment]
> Does this example work for mailgun.js 2.x as well? If not, we may just provide 2 examples, for 2.x, and 3.x, because 3.x has only been release end of Jan 2021.

I am currently trying to get it to work with the current version 3. Have not noticed it was upgraded to 3 that recently.

 I have not tested the example with 2.x as I am migrating from simple-mailgun-adapter to this code here.

**Comment by mtrezza** [comment]
I believe there was an issue with 3.x back then that made me not use it in this package. I believe it was https://github.com/mailgun/mailgun-js/issues/107.

**Comment by funkenstrahlen** [comment]
> I believe there was an issue with 3.x back then that made me not use it in this package. I believe it was mailgun/mailgun-js#107 but that seems to have been merged now, maybe released in 3.1.1.

I use 3.3.0 now and it looks like it's working successfully.

> We may also need an additional ApiPayloadConverter for 3.x.

Why do you think so? Seems to work for me in my first tests right now.

**Comment by mtrezza** [comment]
That's great, I just meant we may need one if the major version change means the driver changed parameters. Even better if it didn't.

**Comment by mtrezza** [comment]
This was the issue I was referring to: https://github.com/mailgun/mailgun-js/issues/113

**Comment by funkenstrahlen** [comment]
> This was the issue I was referring to: [mailgun/mailgun-js#113](https://github.com/mailgun/mailgun-js/issues/113)

I am not using TypeScript in my codebase yet so I do not see the error.

**Comment by mtrezza** [comment]
@funkenstrahlen Any update on this?

**Comment by funkenstrahlen** [comment]
My parse server still runs without any issues using this setup.

Is there anything I can do before this PR can be merged?

**Comment by mtrezza** [comment]
Apologies, I wasn't aware this is ready for review. I'll take a look soon.

**Comment by mtrezza** [comment]
@funkenstrahlen I added your name to the changelog entry. Let me know if you want to remove / change it.

**Comment by funkenstrahlen** [comment]
> @funkenstrahlen I added your name to the changelog entry. Let me know in case you want to remove / change it.

Thank you for adding my name to the changelog. It does not have to be changed.

**Pull request merged**
