### PR TITLE
Allow to supply user object when sending via cloud code

### LINKED ISSUE #20: Locale callback throwing an error when sending email through cloud code
### New Issue Checklist
- [x ] I am not disclosing a [vulnerability](https://github.com/mtrezza/parse-server-api-mail-adapter/security/policy).
- [x ] I am not just asking a [question](https://github.com/mtrezza/parse-server-api-mail-adapter#need-help).
- [x ] I have searched through [existing issues](https://github.com/mtrezza/parse-server-api-mail-adapter/issues?q=is%3Aissue).
- [x ] I can reproduce the issue with the [latest version](https://github.com/mtrezza/parse-server-api-mail-adapter/releases). 

### Issue Description
When I try to send a templated email with locale callback the cloud code throws an error 
cannot find function get of undefined

### Steps to reproduce
setup a custom email template with locale callback. 
```
localeCallback: async (user: any) => {
       return user.get('language');
 }
Call it from the cloud code like so:
    Parse.Cloud.sendEmail({
      templateName: "custom_email",
      recipient: a@b.c,
      placeholders: request.params.placeholders
    });
```
(Only works for current Parse server master branch, parse-server 4.5 doesn't have the sendEmail function yet)

### Actual Outcome
Error, cant find method get of undefined error when the locale callback code is executed

### Expected Outcome
Correct locale email gets sent

### Failing Test Case / Pull Request
#18 

###  Environment

- API Mail Adapter version: 1.0.4
- Parse Server version: Master branch

### Logs
don't have them any more^^

### PR DESCRIPTION
**Pull request by wlky**
Right now locale callbacks are not working for me, I assume due to the fact that user is always undefined when sending vie Cloud code.
This change would allow to supply the email adapter with the user object when sending an email via cloud code (I hope, haven't tested it yet, but it's a very small change)
happy about any feedback

Related issue: closes #20

### CODE REVIEW

**Comment by mtrezza** [comment]
Thanks for submitting this PR.

Would you please also create an issue and reference it in this PR? It helps us to better understand the issue you discovered and your use case.

**Comment by wlky** [comment]
sure, done.
I've also testet this change now and it's working for me.
This change allows setting the user when calling the sendEmail function
    Parse.Cloud.sendEmail({
      templateName: "custom_email",
      recipient: a@b.c,
      placeholders: request.params.placeholders,
      user:  request.user
    });

**Comment by mtrezza** [comment]
This is missing a test case and some docs, can you give me access to your branch and I add this real quick?

**Comment by wlky** [comment]
yeah sorry, wasn't sure how to do that stuff :D
You should have access to the fork now

**Comment by mtrezza** [comment]
Thanks, I added the tests and did some minor changes.
Can you try out if this branch solves the issue for you?

It is now possible to pass the user *and* a recipient in `sendMail` which can seem like a contradiction, because also the user may have an email address:

```
Parse.Cloud.send({ recipient: 'a@example.com', user: aUserWithEmailAddress });
```

To solve his I added the logic that if `recipient` is not set, the email address of the user `user.get('email')` is used as recipient by default.

**Pull request merged**
